name: newerville_head
version: '${project.version}'
main: ru.omashune.headsanywhere.HeadsAnywhere
api-version: 1.16
softdepend: [ PlaceholderAPI, SkinsRestorer ]
authors: [ newermamalchik ]
description: Use players' heads anywhere!
